ifndef MAKEFILE_LEX
define MAKEFILE_LEX
endef

CCFILES = main.cc \
		  lex.cc \
		  number.cc \
		  operator.cc \
		  symbol.cc \
		  word.cc \

INCPATH += -I../symbol -I../

DEFINES += -DLEX

include ../Makefile.common

endif # MAKEFILE_LEX